export const Pdata = [
    {
        id:'1241',
        name:"John Doe 01",
        age:24,
        gender:"Male",
        marital:"Married",
        contact:"+91 5685659555",
        email:"abc@gmail.com",
        address:"Address, NYC",
        BCI:"Caliberated",
        sessionsAttended:5,
        MIAccuracy:"98%",
        MIVSARAT:0.5,
        MIAVSGS:0.45,
        medicaldescription:"Current medical description of patient"
    },
    {
        id:'1242',
        name:"John Doe 02",
        age:24,
        gender:"Male",
        marital:"Married",
        contact:"+91 5685659555",
        email:"abc@gmail.com",
        address:"Address, NYC",
        BCI:"Caliberated",
        sessionsAttended:5,
        MIAccuracy:"98%",
        MIVSARAT:0.5,
        MIAVSGS:0.45,
        medicaldescription:"Current medical description of patient"
    },
    {
        id:'1243',
        name:"John Doe 03",
        age:24,
        gender:"Male",
        marital:"Married",
        contact:"+91 5685659555",
        email:"abc@gmail.com",
        address:"Address, NYC",
        BCI:"Caliberated",
        sessionsAttended:5,
        MIAccuracy:"98%",
        MIVSARAT:0.5,
        MIAVSGS:0.45,
        medicaldescription:"Current medical description of patient"
    },
    {
        id:'1244',
        name:"John Doe 04",
        age:24,
        gender:"Male",
        marital:"Married",
        contact:"+91 5685659555",
        email:"abc@gmail.com",
        address:"Address, NYC",
        BCI:"Caliberated",
        sessionsAttended:5,
        MIAccuracy:"98%",
        MIVSARAT:0.5,
        MIAVSGS:0.45,
        medicaldescription:"Current medical description of patient"
    },
    {
        id:'1245',
        name:"John Doe 05",
        age:24,
        gender:"Male",
        marital:"Married",
        contact:"+91 5685659555",
        email:"abc@gmail.com",
        address:"Address, NYC",
        BCI:"Caliberated",
        sessionsAttended:5,
        MIAccuracy:"98%",
        MIVSARAT:0.5,
        MIAVSGS:0.45,
        medicaldescription:"Current medical description of patient"
    },
];